version: '3'

services:

  couchbase_db:
    image: fpablos/couchbase
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 8095:8095
      - 8096:8096
      - 11210:11210
      - 11211:11211
    deploy:
      mode: global
      # replicas: 1
      restart_policy:
        max_attempts: 3
        condition: on-failure
    networks:
     - balance

  proxy:
    image: fpablos/proxy
    ports:
      - 8081:8081
    depends_on:
      - couchbase_db
    deploy:
      replicas: 50
      restart_policy:
        max_attempts: 3
        condition: on-failure
      update_config:
        parallelism: 3
        delay: 10s
    networks:
     - balance

  # NOTA: Lo comento ya que voy a usar como balanceador de carga el que provee SWARM
  # En caso de no querer usarlo, descomentar y levantar con `docker-compose up -d`
  #
  # balancer:
  #   image: fpablos/balancer
  #   ports:
  #     - 80:80
  #     - 443:443
  #   depends_on:
  #     - proxy
  #   deploy:
  #     placement:
  #       constraints: [node.role == manager]
  #   networks:
  #     - balance

networks:
  balance:
    driver: overlay
